title: VDesign
email: vanyad@gmail.com
destination: docs
description: Interior design portfolio. Awsome interior designs. Furniture design.
baseurl: "/VDesign"
url: ""
github_username:  vanya-ant

# Build settings
plugins:
  - jekyll-feed

collections:
  - gallery

exclude:
  - docs
  - Gemfile
  - Gemfile.lock
  - node_modules
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - gulpfile.js
