title: VDesign
email: vanyad@gmail.com
description: Interior design portfolio. Awsome interior designs. Furniture design.
destination: docs
baseurl: "/VDesign"
url: ""
github_username: vanya-ant

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

collections:
  - gallery
  - projects

exclude:
  - docs
  - Gemfile
  - Gemfile.lock
  - node_modules
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - gulpfile.js
  - .jekyl-cache/
  - .idea/
